### ISSUE TITLE
Service Provider Name Inconsistent

### ISSUE THREAD

**Issue by lloy0076** [eduardoarandah/autohttptests#3]
The capitalisation of the service provider and the actual thing it's providing are not consisiten:

* `AutoHttpTests`; or
* `AuttoHttptests`

Personally I prefer the latter.

**Comment by eduardoarandah** [comment]
Correct.  Capitalized everything by word. 

https://github.com/eduardoarandah/autohttptests/commit/7b1f5ce12833a6ec17d87f30f0425c1be2633769
