### ISSUE TITLE
Confusing Command Name

### ISSUE THREAD

**Issue by lloy0076** [eduardoarandah/autohttptests#4]
https://github.com/eduardoarandah/autohttptests/blob/417832d5fe776684fe9c7e530ebdb8ad0073ec3b/src/AutohttptestsServiceProvider.php#L26

With the thing registered and this only having a single `s` difference it's somewhat confusing.

Consider renaming it (I wouldn't) or fully qualifying one or both of them to make it more obvious.

**Comment by eduardoarandah** [comment]
jeje yes, you're right man! 
these two boys look the same
thanks 
https://github.com/eduardoarandah/autohttptests/commit/609956426277e1ec4f35ff7931c07641439b6cee
