### ISSUE TITLE
Consider Using AST Generator

### ISSUE THREAD

**Issue by lloy0076** [eduardoarandah/autohttptests#7]
See this issue for pros/cons:

https://github.com/Laravel-Backpack/Generators/issues/27

**Comment by eduardoarandah** [comment]
Sounds good, I don't like having code full of \n\t\t, looks silly 
BUT
Everybody understands \n\t\t and keeps it simple


I'll definitely study that package, looks like it will give me some deeper understanding of PHP, are you planning on using it in backpack?
